from app.models.geo import FieldResult, Location


def build_answer(
    question: str,
    location: Location,
    results: dict[str, FieldResult],
) -> str:
    lines = [
        f"For the coordinate {location.lat}, {location.lng}, the location is "
        f"{location.district or 'outside the current Uttar Pradesh district coverage'}.",
    ]

    elevation = results.get("elevation_m")
    if elevation and elevation.value is not None:
        lines.append(f"Elevation is {elevation.value} m.")
    elif elevation:
        lines.append("Elevation is unavailable for this coordinate because the DEM tile is not downloaded yet.")

    road = results.get("nearest_road_distance_m")
    if road and road.value is not None:
        lines.append(f"The nearest mapped road is about {road.value} m away.")
    elif road:
        lines.append("Nearest road distance is unavailable in the current OSM sample coverage.")

    water = results.get("nearest_water_distance_m")
    water_name = results.get("nearest_water_name")
    if water and water.value is not None:
        name = ""
        if water_name and water_name.value:
            name = f" ({water_name.value})"
        lines.append(f"The nearest mapped water feature{name} is about {water.value} m away.")
    elif water:
        lines.append("Nearest water distance is unavailable in the current OSM sample coverage.")

    place = results.get("nearest_place_name")
    if place and place.value:
        lines.append(f"The nearest mapped place label is {place.value}.")

    lines.append("These values come from the cited local datasets; no geospatial value is generated by the language layer.")

    return " ".join(lines)
